* Female Human Dragon Sorcerer

Due to the recent events that turned the world into schorching
desert. Only the strongest of the strongest sorcerers survived, most
survivors have very visible dragon traits that make them stand out
among populace.

** Appearance

I have thick long red hair, saturated green dime-sized dragon scales
except around my mouth, my nose, eyes, ears and couple spots around my
neck and other places on my body where I have smooth skin. People say
that my eyes are burning deep green like XXX (A green shining anomaly
that is now the second sun). My nose is round with slightly dark
spots, my cheeks turn dark green when I blush, not as dark as my
bow-shaped lips tho. People are scared seeing my foot long tail so I
keep it tucked in a cloth wrapped around my waist. I bleed metallic
green.

** Backstory 

I used to be pretty girl with nice pink skin living with mommy in our
village. I was helping watering fields and when I had done enough work
I was allowed to collect desert bug nom noms. Once when I've returned
with a jug of desert bug nom noms the village was empty, I could not
find anyone. Maybe desert ghosts took them away? I was telling them to
leave one desert bug nom nom for the ghosts and they didn't do it!

I found some flour in the house so I made flatbread with bug nom
noms. That's when a strange man with pointy ears entered the village,
he called himself The Elder. What a silly name! He offered me a sweet
rock he called honey. It was so sweet! Not even the sweet green
crystals on mommy's old pan can compare. I was asked to join him on
his travels, I've refused, I can't just leave my village with a
stranger, right?

So anyway, I've packed a waterskin and started following him from
afar, munching on desert bug nom noms and flatbread on the way. After
five days of walking my waterskin became very empty, the stranger was
very strong, he killed about a dozen of bad desert bugs, one of them
had sweet bug juice, he didn't know so I stole it when he moved
on.

When he arrived to a crossroads strange people on strange animals
came and started fighting him. They beat him very bad. Then they put
him in a cage, like that one we put our sweet juice bugs in but it had
wheels. They talked a little bit. I had to hide because some of the
riders went my way. After they dragged him away I went the other way.
After one full day, hiding from people walking on the road, I've
arrived at a strange big village, it had tall walls all around
it. There were funny people with scary pointy sticks in front of the
door to the village.

Shortly after green I've crawled into one of the boxes on wheels that
were entering the town. The guards were searching the boxes. One of
them grabbed my foot when that happened... I felt strange tingling and
burning all around my skin when out of nowhere a green mist from my
palm flew into the guard's eyes, he immediately collapsed to teh
ground gasping for air. I threw a shiny rock at the other guard, it
turned into a strange ball and then there was a flash so I ran away
deeper into the village.

I've ran for a while then hid in one of the strange big shacks. It was
so dark in there I could not see my hands. I've searched the shack and
found something soft I could lie on. So I slept. I was dreaming of
having wings, flying above a strange land. It looked like moving dunes
but very very fast and they were all blue, then I've continued to fly
over a desert that looked like after Green but brighter and the Green
was not even in the sky. I then descended to the desert and noticed
the desert had hair, like those animals that strangers ride on when
they pass through our village. I flew over strange shiny figures and
breathed out a strange, the figures fell down immediately grasping for
air.

I then took off back into the air and met a strange green winged
creature that had huge head and mouth full of teeth, it had teeth on
its back leading to its long green tail connected with leathery stuff.
It looked exactly like me. When we got close we started dancing, twist
left over, twist right under, we took off twisting into the air until
we reached high clouds. Then we started slowly descending, I looked
into its deep green eyes it looked back into mine. It opened its
mouth and said: "Wake up!".

I woke up looking into the Green in the bright sky outside the
window. 

* Female Elf Ranger - Hunter (sister)

Rangers used to be guarding remote areas away from
civilization. Nowadays when civilization is not as common as it used
to be. People who managed to survive by themselves in the schorching
desert are now called rangers. 

** Appearance

** Backstory

I was born as a slave, my brothers were born as slaves, my parents
were slaves. We were forced to do XXX even during the hottest
days. One day my daddy was caught stealing water from the irrigation
canal.

That's when they locked us into that stinky shack without food or
water. The stink of rotting meat coming from the poop hole was
unbearable for the first three days. My daddy succumbed to madness, he
could not bear the situation he got his family into. When I woke up I
found him in the corner of the shack with crushed skull and bloody
rock in his hand. The same day my youngest brother died to an illness,
could that be because his leg slipped into the poo hole a day earlier?

My mother was stone faced nearly the whole time, even after father's
death she was calming us down, putting us to sleep and singing
lullabies with her drying voice. She could not bear the death of her
youngest son, however. She started crying and never stopped. I woke up
in her dry thin arms by insects feeding on her eyeballs. That was the
first meal I and my brother had in two tendays.

Early in the afternoon the slavers kicked us out and made us carry the
corpses of our parents and brother, they were unusally light, yet it
took a lot of strength to lift them. When I looked back I saw another
family being led in.

We laid them on an edge of irrigating channel where most of the corpse
eating insects stay



* Male Elf Barbarian (brother)
