* Female Human Dragon Sorcerer

Due to the recent events that turned the world into scorching
desert. Only the strongest of the strongest sorcerers survived, most
survivors have very visible dragon traits that make them stand out
among the populace.

** Concept

Because she was torn out of her life by a tragedy she had no time to
expand her vocabulary, the story is told using childish terms to
present it from her point of view. She is an escapee that was shortly
sheltered among communities of various people. Though due to her
nature she had too much heat on her and the communities had to exile
her or face (what?) consequences.

When she gets captured it is always the same headhunter (who?) that
she interacts with through the whole story. She manages to escape a
couple of times, never learning where her captor lead her to. The
headhunter knows he that once he will capture her he will be set for
the rest of his life.

Her green skin and dragon scales allow her to survive extremely hot
temperatures in the desert much easier. Though at night, unlike other
creatures, her skin reflects the warm light of Green away and she
needs to use other means to maintain temperature.

** Backstory summary & ideas

Her story begins at eight years old when everyone in her village
mysteriously disappears. She then starts following a stranger calling
himself The Elder who is a survivor of the prior era, hiding that
information from her. At some point The Elder gets captured so she
goes the other way and discovers a city.

Curious, she tries to sneak in after sunset but quickly gets
discovered. That is when her power awakens, she ends up killing two
guards with magic and disappears into an abandoned house. There she
falls asleep and dreams of becoming a dragon flying above blue ocean
and green land, this is described in words she is the familiar with.

After dream dance with another dragon she wakes up, discovering that
her skin is green and she now features dragon scales all over her
body, this discovery feels like an out of body experience at first
before she realizes what had happened.

/Subject to change after this point/

She searches the abandoned house and discovers a big ruby
necklace. After the commotion she caused the previous night the guards
are going door to door searching all houses.

A pair of guards enters her hideout, gets distracted by a pile of
cleaned bones. The pile is hiding flesh fleas that eat their victims
alive. She escapes as the guards are eaten alive.

...Gets saved by a street kid, gets offered a way to lower heat...

...Kicks out a weird kid disguised as her. Gains trust...

...Joins a gang of street kids, living away from commoner's sight...

...Gets exiled because her nature becomes too much of a liability...

...The leader of street kids sells her out, gets captured...

...On the way to the destination the caravan gets ambushed...

...Her captor survives and she is led in chains through the desert...

...Exhausted, the captor passes out, she frees herself...

...Discovers that her new traits help her survive the wasteland...

...Survives combat with desert creatures using magic, eats them...

...Reaches a village, stays there for some time...

...Rumors of her presence leads headhunters on her trail...

...Gets sold out by a local, her former captor is alive...

...Something...

...Escapes...

...Lives from the wasteland...

...Reaches 16 years of age...

** Appearance

I have thick long red hair, saturated green dime-sized dragon scales
except around my mouth, my nose, eyes, ears and couple spots around my
neck and other places on my body where I have smooth skin. People say
that my eyes are burning deep green like Green (A green shining anomaly
that is now the second sun). My nose is round with slightly dark
spots, my cheeks turn dark green when I blush, not as dark as my
bow-shaped lips tho. I bleed metallic green.

** Backstory 

~shorten the sentences to fit 8 year old, "before I get my scales"~
I used to be pretty girl with nice pink skin living with mommy in our
village. I was helping watering fields and when I had done enough work
I was allowed to collect desert bug nom noms. Once when I've returned
with a jug of desert bug nom noms the village was empty, I could not
find anyone. Maybe desert ghosts took them away? I was telling them to
leave one desert bug nom nom for the ghosts and they didn't do it!

I found some flour in the house so I made flatbread with bug nom
noms. That's when a strange man with pointy ears entered the village,
he called himself The Elder. What a silly name! He offered me a sweet
rock he called honey. It was so sweet! Not even the sweet green
crystals on mommy's old pan can compare. I was asked to join him on
his travels, I've refused, I can't just leave my village with a
stranger, right?

So anyway, I've packed a water skin and started following him from
afar, munching on desert bug nom noms and flatbread on the way. After
five days of walking my water skin became very empty, the stranger was
very strong, he killed about a dozen of bad desert bugs, one of them
had sweet bug juice, he didn't know so I stole it when he moved
on.

When he arrived to a crossroads strange people on strange animals
came and started fighting him. They beat him very bad. Then they put
him in a cage, like that one we put our sweet juice bugs in but it had
wheels. They talked a little bit. I had to hide because some of the
riders went my way. After they dragged him away I went the other way.
After one full day, hiding from people walking on the road, I've
arrived at a strange big village, it had tall walls all around
it. There were funny people with scary pointy sticks in front of the
door to the village.

Shortly after green I've crawled into one of the boxes on wheels that
were entering the town. The guards were searching the boxes. One of
them grabbed my foot when that happened... I felt strange tingling and
burning all around my skin when out of nowhere a green mist from my
palm flew into the guard's eyes, he immediately collapsed to the
ground gasping for air. I threw a shiny rock at the other guard, it
turned into a strange ball and then there was a flash so I ran away
deeper into the village.

I've ran for a while then hid in one of the strange big shacks. It was
so dark in there I could not see my hands. I've searched the shack and
found something soft I could lie on. So I slept. I was dreaming of
having wings, flying above a strange land. It looked like moving dunes
but very very fast and they were all blue, then I've continued to fly
over a desert that looked like after Green but brighter and the Green
was not even in the sky. I then descended to the desert and noticed
the desert had hair, like those animals that strangers ride on when
they pass through our village. I flew over strange shiny figures and
breathed out a strange cloud, the figures fell down immediately
grasping for air.

~interpunction, reword the dance part~
I then took off back into the air and met a strange green winged
creature that had huge head and mouth full of teeth, it had teeth on
its back leading to its long green tail connected with leathery stuff.
It looked exactly like me. When we got close, we started dancing. Twist
left over, twist right under, we took off twisting into the air until
we reached high clouds. Then we started slowly descending, I looked
into its deep green eyes it looked back into mine. It opened its
mouth and said: "Awaken!".

I woke up, observing Green slowly pulsating in the morning sky through
a hole in the boarded window. I've stretched my arm out toward it and
watched a green arm slowly extend out in front of me. That scared me a
little and the arm quickly retracted. I've turned on my back, closed
my eyes and slowly raised my hands above me. When I've opened my
eyes I was looking at a pair of green hands. They had scales,
like the creature in the dream but smaller, extending from back of the
hands, continuing up to the arms as far as I could see. The only place
with no scales were the fingers and the palms which were covered by
green skin. I've clasped my hands into fists, the hands immediately
formed fists. I've opened my hands back again, the hands
relaxed. Those hands were mine! My hands were green!

I've immediately sat up and realized that not only my hands but almost
my whole body was covered with green scales. Some of the scales were
small like my pinky toenail or as big as my big toenail. I've touched
my face and felt hard scales on my forehead as I was touching my face
some more I felt smooth skin around my eyes, on my nose and
cheeks. When I've reached my neck I felt hard scales again. I've
looked in front of me and on the opposite side of the room I've
noticed curled up skeleton, the white bones were stripped clean. Its
right skeletal arm was reaching for a necklace with big red gem. I've
stepped around it, very carefully, I didn't want a flesh flea to bite
me. I've reached out to the necklace and it was mine.

That is when the door to the shack opened and I've heard two pairs of
boots step in. I hid in the closet and stared outside through a small
hole. I watched two strong men enter the room I was sleeping in. They
noticed the skeleton near the wall and looked more closely. A black
shadow-like monster started crawling from behind the bones covering
the floor like a rug. One of the men called out something but it was
too late.

Small dots started jumping from the monster, they started screaming
but the dots entered their mouths and the men caughed. Blood was
coming out with each of their cough, the monster disappeared and their
bodies was crawling with flesh fleas. A horrible fate that reminded me
of our neighbor, we had to set his house on fire. One of the men
looked at me sitting in the closed horrified, he opened his mouth and
tried to say something but all I've heard was gurgling. I left the
closet and ran.

When I've peeked outside the shack door I saw two groups of similarly
dressed men walking from shack to shack. Were they looking for
someone? I ran thourough the village, people were stepping away from
me, my path was clear. I heard screams from around me as if the people
weer scared of me, I didn't pay attention to that. After a while I saw
a lot of men standing shoulder to shoulder next to each other blocking
the street. They were looking at me. I've turned around and ran
back. I ran for a short a while when saw another group of men doing
the same, they were coming closer. I've turned around and ran into a
small street but after a short while I've saw a shack blocking my
way. I had nowhere to run. Suddendly a hand extended from a shadow
under one of the shack, I've grabbed it.

It pulled me into a stinky dark room. After I could see in the dark
again I saw a boy. Loud noises started coming from the hole I was
pulled through, louder and louder. "Don't just stand here! They're
gonna catch us!" said the boy. And I ran through a strange tunnel that
looked a bit like our well but it was the wrong way! I followed him
for a long time, crawling through small windows, stepping over stinky
water. After a couple more of turns and climbing we've left the hole
and found ourselves back under the hot sun. We entered a shack with
strange symbols on the door and walked in front of three more boys and
two girls.

"Why did you lead her here, Jade? You clearly must know that it is her
whom are they turning the sity upside-down for?" said one of the older
boys.

"She could be quite useful to us." the boy who saved me said. "I've
seen what she caused at the gate, she easily killed two guards and
sneaked away. Even I had trouble finding her."

"Maybe! But what to do with her now? They are unlikely to stop until
they find her." responded one of the younger boys.

"We can exile Jack, he has been rotting in the cell of yours for days
anyway." Jade said.

"And how are you going to do that? Do you think the guards can be so
easily fooled now, that they've seen her?" said the older boy again.

"It is quite easy, we will tie sewer moss over his body and let him
escape through one of the tunnels leaving the city." Answered Jade "He
knows what happens to him when he returns and giving himself up to a
bunch of guards just gets him killed. Once they'll spot him running
away toward the desert worm plains they'll likely leave him alone."

"And I will spread rumors that it was her who ran towards certain
death." said one of the girls with big belly. "You're smarter than
I thought Jade!"

"Let's get to it! I don't want them entering our hideout again!" said
the younger boy looking straight at me "You better go help Jade
if you want to stay with us!".

"Here!" said the younger girl. She removed a board from the floor of
the shack and I could see a ladder leading under the shack.

"Let me go first" said Jade, grabbed a handle and helped himself into
the hole. I've carefully crawled one bar after another until I've got
to the bottom. When I've looked around I saw Jade removing stones from
a wall in the corner.

"So you already know my name. Sorry, there was no time for
introductions, and we are not out of the trouble yet." he said. "There
is a sewer tunnel behind this wall. In one of the dead ends is a boy
chained to a wall. I'm going to release him. Here is a knife, scrub a
bit of the sewer moss from the wall for me."

As he said that he crawled through the hole we made, I followed
him. The stink felt even worse than the first time. ~At an
intersection, jade left~ I've changed grip on the knife and started
scraping the green wall ~living from light coming through cracks~.
It was coming off easily. Before I could hear two sets of steps behind
me I had a reasonable pile of what they called sewer moss. I've
expected him to say something but the silence was only interrupted by
the steps.

I've looked over my shoulder and stared into two eyes reflecting a bit
of the dim light coming from above. It had long nose and whiskers
coming from one wall of the tunnel to the other. Fur coming from its
nose and disappearing in the darkness between its eyes. I've dropped
everything I had and ran forward. I've turned into a tunnel and kept
running. I've heard the steps coming closer. I put all my strength to
my legs and ran even faster. I've reached a room where there leading
three more tunnels out. I took my left. I took a couple more steps but
then slipped on a slimy pile of stinky goo and fell.

The creature jumped on top of me, scratching. I retched as the smell
~directly breathed at me~
from its mouth went directly to my face. I was looking at two huge
teeth coming out of the creature's mouth. As the mouth closed in on my
face trying to bite my head off I stabbed it with Jade's knife I
clenched in my hand. I felt the knife go in smoothly then hitting
something hard. The creature immediately backed up, revealing its
whole furry body. It was looking at me with anticipation ~?~, right
eye leaking out.

My heart was beating as the creature prepared to leap I put my hands
in front of me, trying to stop it with all my being ~this section is a
bit odd, but whatever~. My hands started glowing dark green, I felt
something as if my blood wanted to escape from my chest through my
arms and hands out of my body. A strange pulsating glowy liquid
escaped from my hands and hit the creature in its head, it entered
through its skin and left no trace. The creature started violently
shaking and fell on its back, twitching its huge dirty feet. I watched
as the twitching was slowing down until it completely stopped. ~fell
to the knees~ I've heard a familiar voice behind me "So you've met
Jake?".

~It's dark~
I've turned around and saw one of the boys that were with me in their
shack "You're surprising me, love! I thought Jade would've let you get
lost in the tunnels but you really do prove to be quite resourceful!"
he continued "Name's Bob, by the way! It looks like our Jade went too
ahead of himself again and forgot to tell you about our friendly
neighbor rat." ~slight contradiction here~ He looked down on the
creature's head "I have no idea how Jake escaped the barricaded tunnel
but it seems that the way under the Market is now open! Oh, and don't
worry, this is not the Jake we were talking about up above!". He put
his hand on my arm "Time to go love! You still have a Jake to kick
out! I'll take care of things so you can have a MEATY meal
tonight!". I stood up, the boy walked past me "Go straight, then take
two left turns then straight again and at an intersection with bright
light from above turn right. You shoud be back where you've started."

I've walked through the darkness, following Bob's directions. When
I've entered the bright room I saw a pile of sand underneath a mesh up
on the ceiling. Whh-PSHH! Sound came through the barred hole in the
ceiling. A face blocked the hole, I saw a woman breathing in and out
"Stop sniffing the shit down there and walk faster! The crops won't
harvest themselves!" a fainted voice from behind her said, then a shoe
with a hard kick moved the woman's face off the grate
~consistency~. After a short pause the voice, now more louder, said "Oh
yeah? And what you gonna do about it? Dan said that he's gonna go to
the market and buy more anyway!".

As I've continued to the right tunnel I've heard more moans and sounds
coming from above, as if someone was beating a sack of grain. I've
continued through the dark tunnel and reached an intersection where
were two figures waiting for me. "Hey! You've escaped! I thought
you're goner there!" said Jade and turned his head to the other boy
"Say hell to Jake ~Using the same name is confusing~ here! His
shackles were all rusted up so I needed something to break them
open. I guess the stone was important for the barricade that held the
rat on the other side." he explained "I guess it was not in the next
tunnel. Should've marked that." he jerked the chain in his hand in
front of him and the boy fell on his hands "Introduce yourself to the
lady!"

The boy slowly raised his head "So you're the witch that came here to
curse this city? Is it gonna be drought? Or are you going to infect
poor Jade with plague?" ~This is something that crazy old man would
say~

In that moment Jade kicked him in the face "Be polite! She is our
guest and you're going to be nice to her!"

He raised himself on his knees "So you've have already enchanted him,
huh? What a loss! He could be a nice thief if he hadn't his eye for
green monsters like you!"

"Alright! Now you've pissed me off!" Jade screamed and kicked him in
the stomach at full force.

The boy fell on his side "You better not finish me off here! I guess
you didn't cause youreslf so much trouble just to show me your new
girlfriend." came out of his mouth faintly.

~character conistency!~
"That is right Jakey! We're here to set you free!" Jade said and took
a proud pose! "That reminds me, we're quite in a hurry, would you mind
picking yourself up and get your ass moving?" He pulled on his chain
and made Jake, grabbing his throat, stand up. "Let's go! We have quite
a march in front of us!"

Jade led the way, we were walking through twists and turns. Crawling
through tight spaces and more dark tunnels. After some time we entered
a strange big room with ceiling supported by big rock. A big dark hole
opened in front of us.

"We call this the Dark Hole. We don't know what lives there but it
cannot be good. Here Jakey would tell you more if he wasn't a complete
nut job." Jade spat down into it then looked at Jake "If it is true
what James said about his race being noble protectors of the forests
then his kin would not be really happy with him ~why?~."

For the whole time we were walking around the Dark Hole Jake was very
quiet. Once we left through the tunnel leading out he started quietly
sobbing. We quietly arrived to an opening in a wall, when we crawled
through we found ourselves in a strange place. There were big stone
coffers. This whole place was very dark ~describe the darkness~ Jade
led us through dark corridor and then we found ourselves climbing
stone steps. I've tripped over a wooden thingy.

Jade put his chain in my hands and said "Don't let him run!".

He lifted the huge wooden thingy and pushed it into the ceiling, he
then started cranking a crank. A lot of sand started falling down but
he kept cranking away. After a moment a speck of light entered the
room that started slowly widening up. I could se Jake's face now. His
dirty face was revealing a deep black scar across his left cheek, his
hair was very uncombed, it was held back by his long pointy ears. His
eyes had no dots, they looked like glowing blue clouds. "Are you
putting a curse on me, witch?" he snapped at me and I've looked back
at Jade.

Clack! He finished doing his thing and picked up a ladder lying
alongside the wall, he put it inside wooden thingy that is now a
tunnel up. He grabbed moss from a bag he had strapped to his back and
started tying it around him with small threads. When he used up all
the moss he grabbed the bag and put put it on his head, secured it
with a thread, it looked like a hat.

Jade took the chain from my hand, looked at Jake and said "You're
gonna be free soon!".

~wait until early afternoon~
He started climbing the ladder, pulling on Jake's chain who was
climbing up behind him. I was slowly following them. We climbed up
next to a big hot rock. The sun was above our heads. "Give him your
waterskin!" said Jade. I removed my half empty waterskin from my
shoulder and handed it out to Jake.

~locate the city from this position~
Jade removed his bonds and said "You're now free! Go! And never
return!".

Jake responded "As if I wanted to stay with your witch!" and started
walking.

~notices injury from combat with rat~
We've climbed back down and sat next to a wall. I was looking at the
wall. There were strange statues in the side of the stone. It was a
group of people carrying a box. Inside the box I could see a
skeleton. There was a picture of a strange flying creature. ~discard~
I felt Jade put his hand on mine "I think they called this place a
crypt" he said "A place where they would bury their dead". After a
short rest I've helped Jade to remove the wooden tunnel from ceiling
and the room fell back into darkness.

After waiting for a while until I could see again, we started walking
down the stairs back, crawled through the hole we came through. As we
were walking around the Dark Hole strange faint noises were echoing
from down below. Like if someone fought a monster in the
distance. When were closing in on the tunnel leaving the Dark Hole we
could hear voices coming out.

"Are you sure it is safe down here? What if we get caught by the
sewer monster?" said one voice.

"And what do you suggest? To get burned alive by those purging fires
instead? There must be an exit around here somewhere." the other voice
replied.

We hid next to the entrance to the tunnel, our backs next to the wall
when we saw two figures come through, they've approached the Dark Hole
"How deep do you think this is?" said the shorter man.

"There is easy way to tell, just let me..." as he said that Jade
pushed him with all force into the hole.

~Rewrite, everyone is a badass after all~
The man started screaming, stepping away from the hole, looking around
himself erraticaly. But he couldn't spot Jade hiding in the darkness
next to him. Jade jumped on his back and stabbed him in the neck. The
man started grabbing which se succeded and threw Jade off of him. Jade
landed into a pile of dry refuse.

The man pulled something from his back pocket and jumped on Jade and
holding his throat said "You're not going to take me down that easily,
boy!"

Jade screamed, looking at me with his terrified face. The man followed
his gaze and looked at me. "So you're here with your whore! What if I
kill you in front of her?"

I fell to my knees "Please sir, don't kill him! He saved my life!"
I've started crying.

"Oh, what a honorable knight you are! I have an idea!" said the man
and grabbed a rope attached to his belt. "How about a tragic story
where the good hero was restrained and could only watch how his
princess gets molested in front of him!" he continued.
~and tortured~

I started crying even more "Please sir, let him go!".

The man tied Jade's hands to a piece of metal on the floor and
approached me. I felt strong hand grasping around my arm. "Don't worry
little one, it will only take the whole afternoon. I'm not in a
hurry." and put his other hand on my side. He leaned on me.

"Quickly! Kick that worm!" screamed out Jade.

~A bit cheezy~
I've extended my leg forward and kicked him in his leg. He laughed
"You can try as much as you want, they don't call me The Rock for
nothing". I fell forward but my arm was still in his hand. I've turned
around and stabbed him is the hand with a fragment of Jade's knife.

"Oh, no no no! You're not going to give her any more ideas" the man
yelled out and moved his hand from my arm to my wrist. He jerked me
and I fell on the dirty floor. "You stay there, honey! I'm not done
with you!" he said and with a full force punched Jade in his
face. Jade's legs became limp and he fell to his knees. "Good boy!
Don't worry! You can watch me and learn!" he said and walked up to
me.

"Please! Stop doing this! I don't like it!" I hid behind my crossed
arms.

~This encounter forces character development way too soon~
"Oh, that is because you never tried it before! I'm sure you will love
it!" said and grabbed both of my hands. I've started
resisting. "C'mon, you whore! Don't you dare..." as he said that. I
felt something escape my hand. The man started coughing "What did you
do to me?!" released my hands and started swaying in pain. "You're the
witch that escaped!". As he was trying to compose himself unsucessfuly
I've removed my family's knife from my sack and ran against him. I've
stabbed him in an eye. He put his hands over his face, still stumbling
around closer to the Dark Hole. "You're going to pay for this! Brat!"
as he got closer to the hole I've pushed him into the hole.

He screamed. I didn't pay attention to that, I ran up to jade and cut
the rope from his hands. He fell on his stomach. I held up his left
arm and we walked out of the Dark Hole area. A faint thud echoed from
the room.

~it's not that late! or is it?~
We went through twists and turns. Crawled through tight tunnels and
found ourselves under a faint green light from above. The wall next to
us stil beared a marking of scraped of the moss. We're close!

We went into a tunnel, crawled through a hole, climbed up a ladder and
entered a familiar place. A girl with big belly was sitting in the
corner "They went out without you. They expected you will return much
sooner!" she looked at Jade closely "Did you get into a fight again?
You're lucky you have a new guardian angel with you."

She looked at me "I keep telling him to not pick fights with the
adults! That he's not gona return back one day!"

"And I keep telling you that if it weren't me, you would still had to
wait until dark to go out!" spat out Jade and sat on the floor. "Your
story about the sewer monster would just stay a fairy tale."

As I was sitting on my knees the world started disappearing in front
of me...

~Add dream scene here~

I slowly opened my eyes. I saw a person sitting beside me, all
blurry. She said something and put her hand and on mine. I've passed
out again.
~everything disappeared again~

~More dream scene~

I woke up. Sun shining in my eye through a crack in the roof. I looked
around and on my side was sitting the girl with big belly. "Finally!
You're awake!" She opened her arms. "Don't move just yet, I have to
remove that from you!" And she untied rugs around my arms. "You've
nearly set the roof on fire" she continued and pointed towards a black
spot on a wall across from me.

I sat up... a horrendous pain entered my head. I sat there for a while
waiting for the pain to stop. The girl brought me a flatbread and a
cup of water. "Eat! You have been sleeping for nearly two weeks!" I've
put the cup in my dry mouth and drank all the water in three long
gulps. "Drink slower! We're low on water since Jade got captured!"
Said the girl. Darkness fell over my head...

Now two girls were standing over me. "Poor baby, she passed out as
soon as she head that Jade is gone." said the girl with big belly to
the other then looked at me "She's waking up, get me that stool over
there!" the other girl disappeared, I've heard some creaking and
shuffling and then the girl sat next to me. "You haven't eaten yet!
Take this! You must strengthen up!" and handed me a piece of
flatbread. I put it in my mouth and started munching on it. It was a
bit hard and dry. I've got handed a cup of water, it helped me to
soften the bread a little bit. And with each gulp I ate more and
more. Then my belly started hurting a little bit and I burped.
~Water supply is low, idea: she hates this kind of bread~

"You're not used to eat that much. You will need some more time to get
to your full strength" said the blonde girl. "Do you think you can get
up?" she said.

I sat up, my head started hurting again but I could bear it. I put my
hands on my head so it would hurt less. After a while I put my feet on
the ground, I felt cool ground underneath me. I've looked around and
spotted loose stones in the wall with black shadows between the
cracks. There was a ladder in the opposite corner. We were in the
basement!

"You don't have to climb upstairs just yet!" said the girl with big
belly and continued "I can call others and we can meet down here."

I've nodded and put my hand on my chest. It was bumpy. I had a lot of
small hard bumps nearly all over my chest.





* Female Elf Ranger - Hunter (sister)

Rangers used to be guarding remote areas away from
civilization. Nowadays when civilization is not as common as it used
to be. People who managed to survive by themselves in the scorching
desert are now called rangers. 

** Appearance

** Backstory

I was born as a slave, my brothers were born as slaves, my parents
were slaves. We were forced to do XXX even during the hottest
days. One day my daddy was caught stealing water from the irrigation
canal.

That's when they locked us into that stinky shack without food or
water. The stink of rotting meat coming from the poop hole was
unbearable for the first three days. My daddy succumbed to madness, he
could not bear the situation he got his family into. When I woke up I
found him in the corner of the shack with crushed skull and bloody
rock in his hand. The same day my youngest brother died to an illness,
could that be because his leg slipped into the poo hole a day earlier?

My mother was stone faced nearly the whole time, even after father's
death she was calming us down, putting us to sleep and singing
lullabies with her drying voice. She could not bear the death of her
youngest son, however. She started crying and never stopped. I woke up
in her dry thin arms by insects feeding on her eyeballs. That was the
first meal I and my brother had in two ten-days.

Early in the afternoon the slavers kicked us out and made us carry the
corpses of our parents and brother, they were unusually light, yet it
took a lot of strength to lift them. When I looked back I saw another
family being led in.

We laid them on an edge of irrigating channel where most of the corpse
eating insects stay



* Male Elf Barbarian (brother)
