* Female Human Dragon Sorcerer

Due to the recent events that turned the world into scorching
desert. Only the strongest of the strongest sorcerers survived, most
survivors have very visible dragon traits that make them stand out
among the populace.

** Concept

Because she was torn out of her life by a tragedy she had no time to
expand her vocabulary, the story is told using childish terms to
present it from her point of view. She is an escapee that was shortly
sheltered among communities of various people. Though due to her
nature she had too much heat on her and the communities had to exile
her or face (what?) consequences.

When she gets captured it is always the same headhunter (who?) that
she interacts with through the whole story. She manages to escape a
couple of times, never learning where her captor lead her to. The
headhunter knows he that once he will capture her he will be set for
the rest of his life.

Her green skin and dragon scales allow her to survive extremely hot
temperatures in the desert much easier. Though at night, unlike other
creatures, her skin reflects the warm light of Green away and she
needs to use other means to maintain temperature.

** Backstory summary & ideas

Her story begins at eight years old when everyone in her village
mysteriously disappears. She then starts following a stranger calling
himself The Elder who is a survivor of the prior era, hiding that
information from her. At some point The Elder gets captured so she
goes the other way and discovers a city.

Curious, she tries to sneak in after sunset but quickly gets
discovered. That is when her power awakens, she ends up killing two
guards with magic and disappears into an abandoned house. There she
falls asleep and dreams of becoming a dragon flying above blue ocean
and green land, this is described in words she is the familiar with.

After dream dance with another dragon she wakes up, discovering that
her skin is green and she now features dragon scales all over her
body, this discovery feels like an out of body experience at first
before she realizes what had happened.

/Subject to change after this point/

She searches the abandoned house and discovers a big ruby
necklace. After the commotion she caused the previous night the guards
are going door to door searching all houses.

A pair of guards enters her hideout, gets distracted by a pile of
cleaned bones. The pile is hiding flesh fleas that eat their victims
alive. She escapes as the guards are eaten alive.

...Joins a gang of street kids, living away from commoner's sight...

...Gets exiled because her nature becomes too much of a liability...

...The leader of street kids sells her out, gets captured...

...On the way to the destination the caravan gets ambushed...

...Her captor survives and she is led in chains through the desert...

...Exhausted, the captor passes out, she frees herself...

...Discovers that her new traits help her survive the wasteland...

...Survives combat with desert creatures using magic, eats them...

...Reaches a village, stays there for some time...

...Rumors of her presence leads headhunters on her trail...

...Gets sold out by a local, her former captor is alive...

...Something...

...Escapes...

...Lives from the wasteland...

...Reaches 16 years of age...

** Appearance

I have thick long red hair, saturated green dime-sized dragon scales
except around my mouth, my nose, eyes, ears and couple spots around my
neck and other places on my body where I have smooth skin. People say
that my eyes are burning deep green like Green (A green shining anomaly
that is now the second sun). My nose is round with slightly dark
spots, my cheeks turn dark green when I blush, not as dark as my
bow-shaped lips tho. I bleed metallic green.

** Backstory 

I used to be pretty girl with nice pink skin living with mommy in our
village. I was helping watering fields and when I had done enough work
I was allowed to collect desert bug nom noms. Once when I've returned
with a jug of desert bug nom noms the village was empty, I could not
find anyone. Maybe desert ghosts took them away? I was telling them to
leave one desert bug nom nom for the ghosts and they didn't do it!

I found some flour in the house so I made flatbread with bug nom
noms. That's when a strange man with pointy ears entered the village,
he called himself The Elder. What a silly name! He offered me a sweet
rock he called honey. It was so sweet! Not even the sweet green
crystals on mommy's old pan can compare. I was asked to join him on
his travels, I've refused, I can't just leave my village with a
stranger, right?

So anyway, I've packed a water skin and started following him from
afar, munching on desert bug nom noms and flatbread on the way. After
five days of walking my water skin became very empty, the stranger was
very strong, he killed about a dozen of bad desert bugs, one of them
had sweet bug juice, he didn't know so I stole it when he moved
on.

When he arrived to a crossroads strange people on strange animals
came and started fighting him. They beat him very bad. Then they put
him in a cage, like that one we put our sweet juice bugs in but it had
wheels. They talked a little bit. I had to hide because some of the
riders went my way. After they dragged him away I went the other way.
After one full day, hiding from people walking on the road, I've
arrived at a strange big village, it had tall walls all around
it. There were funny people with scary pointy sticks in front of the
door to the village.

Shortly after green I've crawled into one of the boxes on wheels that
were entering the town. The guards were searching the boxes. One of
them grabbed my foot when that happened... I felt strange tingling and
burning all around my skin when out of nowhere a green mist from my
palm flew into the guard's eyes, he immediately collapsed to the
ground gasping for air. I threw a shiny rock at the other guard, it
turned into a strange ball and then there was a flash so I ran away
deeper into the village.

I've ran for a while then hid in one of the strange big shacks. It was
so dark in there I could not see my hands. I've searched the shack and
found something soft I could lie on. So I slept. I was dreaming of
having wings, flying above a strange land. It looked like moving dunes
but very very fast and they were all blue, then I've continued to fly
over a desert that looked like after Green but brighter and the Green
was not even in the sky. I then descended to the desert and noticed
the desert had hair, like those animals that strangers ride on when
they pass through our village. I flew over strange shiny figures and
breathed out a strange cloud, the figures fell down immediately
grasping for air.

I then took off back into the air and met a strange green winged
creature that had huge head and mouth full of teeth, it had teeth on
its back leading to its long green tail connected with leathery stuff.
It looked exactly like me. When we got close we started dancing, twist
left over, twist right under, we took off twisting into the air until
we reached high clouds. Then we started slowly descending, I looked
into its deep green eyes it looked back into mine. It opened its
mouth and said: "Awaken!".

I woke up, observing Green slowly pulsating in the morning sky through
a hole in the boarded window. I've stretched my arm out toward it and
watched a green arm slowly extend out in front of me. That scared me a
little and the arm quickly retracted. I've turned on my back, closed
my eyes and slowly raised my hands above me. When I've opened my
eyes I was looking at a pair of green hands. They had scales,
like the creature in the dream but smaller, extending from back of the
hands, continuing up to the arms as far as I could see. The only place
with no scales were the fingers and the palms which were covered by
green skin. I've clasped my hands into fists, the hands immediately
formed fists. I've opened my hands back again, the hands
relaxed. Those hands were mine! My hands were green!

I've immediately sat up and realized that not only my hands but almost
my whole body was covered with green scales. Some of the scales were
small like my pinky toenail or as big as my big toenail. I've touched
my face and felt hard scales on my forehead as I was touching my face
some more I felt smooth skin around my eyes, on my nose and
cheeks. When I've reached my neck I felt hard scales again. I've
looked in front of me and on the opposite side of the room I've
noticed curled up skeleton, the white bones were stripped clean. Its
right skeletal arm was reaching for a necklace with big red gem. I've
stepped around it, very carefully, I didn't want a flesh flea to bite
me. I've reached out to the necklace and it was mine.

That is when the door to the shack opened and I've heard two pairs of
boots step in. I hid in the closet and stared outside through a small
hole. I watched two strong men enter the room I was sleeping in. They
noticed the skeleton near the wall and looked more closely. A black
shadow-like monster started crawling from behind the bones covering
the floor like a rug. One of the men called out something but it was
too late.

Small dots started jumping from the monster, they started screaming
but the dots entered their mouths and the men caughed. Blood was
coming out with each of their cough, the monster disappeared and their
bodies was crawling with flesh fleas. A horrible fate that reminded me
of our neighbor, we had to set his house on fire. One of the men
looked at me sitting in the closed horrified, he opened his mouth and
tried to say something but all I've heard was gurgling. I left the
closet and ran.

When I've peeked outside the shack door I saw many similarly dressed
men walking from shack to shack. Were they looking for someone?





* Female Elf Ranger - Hunter (sister)

Rangers used to be guarding remote areas away from
civilization. Nowadays when civilization is not as common as it used
to be. People who managed to survive by themselves in the scorching
desert are now called rangers. 

** Appearance

** Backstory

I was born as a slave, my brothers were born as slaves, my parents
were slaves. We were forced to do XXX even during the hottest
days. One day my daddy was caught stealing water from the irrigation
canal.

That's when they locked us into that stinky shack without food or
water. The stink of rotting meat coming from the poop hole was
unbearable for the first three days. My daddy succumbed to madness, he
could not bear the situation he got his family into. When I woke up I
found him in the corner of the shack with crushed skull and bloody
rock in his hand. The same day my youngest brother died to an illness,
could that be because his leg slipped into the poo hole a day earlier?

My mother was stone faced nearly the whole time, even after father's
death she was calming us down, putting us to sleep and singing
lullabies with her drying voice. She could not bear the death of her
youngest son, however. She started crying and never stopped. I woke up
in her dry thin arms by insects feeding on her eyeballs. That was the
first meal I and my brother had in two ten-days.

Early in the afternoon the slavers kicked us out and made us carry the
corpses of our parents and brother, they were unusually light, yet it
took a lot of strength to lift them. When I looked back I saw another
family being led in.

We laid them on an edge of irrigating channel where most of the corpse
eating insects stay



* Male Elf Barbarian (brother)
