* Female Human Dragon Sorcerer

Due to the recent events that turned the world into scorching
desert. Only the strongest of the strongest sorcerers survived, most
survivors have very visible dragon traits that make them stand out
among the populace.

** Concept

Because she was torn out of her life by a tragedy she had no time to
expand her vocabulary, the story is told using childish terms to
present it from her point of view. She is an escapee that was shortly
sheltered among communities of various people. Though due to her
nature she had too much heat on her and the communities had to exile
her or face (what?) consequences.

When she gets captured it is always the same headhunter (who?) that
she interacts with through the whole story. She manages to escape a
couple of times, never learning where her captor lead her to. The
headhunter knows he that once he will capture her he will be set for
the rest of his life.

Her green skin and dragon scales allow her to survive extremely hot
temperatures in the desert much easier. Though at night, unlike other
creatures, her skin reflects the warm light of Green away and she
needs to use other means to maintain temperature.

** Backstory summary & ideas

Her story begins at eight years old when everyone in her village
mysteriously disappears. She then starts following a stranger calling
himself The Elder who is a survivor of the prior era, hiding that
information from her. At some point The Elder gets captured so she
goes the other way and discovers a city.

Curious, she tries to sneak in after sunset but quickly gets
discovered. That is when her power awakens, she ends up killing two
guards with magic and disappears into an abandoned house. There she
falls asleep and dreams of becoming a dragon flying above blue ocean
and green land, this is described in words she is the familiar with.

After dream dance with another dragon she wakes up, discovering that
her skin is green and she now features dragon scales all over her
body, this discovery feels like an out of body experience at first
before she realizes what had happened.

/Subject to change after this point/

She searches the abandoned house and discovers a big ruby
necklace. After the commotion she caused the previous night the guards
are going door to door searching all houses.

A pair of guards enters her hideout, gets distracted by a pile of
cleaned bones. The pile is hiding flesh fleas that eat their victims
alive. She escapes as the guards are eaten alive.

...Gets saved by a street kid, gets offered a way to lower heat...

...Kicks out a weird kid disguised as her. Gains trust...

...Joins a gang of street kids, living away from commoner's sight...

...Gets exiled because her nature becomes too much of a liability...

...The leader of street kids sells her out, gets captured...

...On the way to the destination the caravan gets ambushed...

...Her captor survives and she is led in chains through the desert...

...Exhausted, the captor passes out, she frees herself...

...Discovers that her new traits help her survive the wasteland...

...Survives combat with desert creatures using magic, eats them...

...Reaches a village, stays there for some time...

...Rumors of her presence leads headhunters on her trail...

...Gets sold out by a local, her former captor is alive...

...Something...

...Escapes...

...Lives from the wasteland...

...Reaches 16 years of age...

** Appearance

I have thick long red hair, saturated green dime-sized dragon scales
except around my mouth, my nose, eyes, ears and couple spots around my
neck and other places on my body where I have smooth skin. People say
that my eyes are burning deep green like Green (A green shining anomaly
that is now the second sun). My nose is round with slightly dark
spots, my cheeks turn dark green when I blush, not as dark as my
bow-shaped lips tho. I bleed metallic green.

** Backstory 

~add friends~
~shorten the sentences to fit 8 year old, "before I get my scales"~
I used to be pretty girl with nice pink skin living with mommy in our
village. I was helping watering fields and when I had done enough work
I was allowed to collect desert bug nom noms. Once when I've returned
with a jug of desert bug nom noms the village was empty, I could not
find anyone. Maybe desert ghosts took them away? I was telling them to
leave one desert bug nom nom for the ghosts and they didn't do it!

I found some flour in the house so I made flatbread with bug nom
noms. That's when a strange man with pointy ears entered the village,
he called himself The Elder. What a silly name! He offered me a sweet
rock he called honey. It was so sweet! Not even the sweet green
crystals on mommy's old pan can compare. I was asked to join him on
his travels, I've refused, I can't just leave my village with a
stranger, right?

So anyway, I've packed a water skin and started following him from
afar, munching on desert bug nom noms and flatbread on the way. After
five days of walking my water skin became very empty, the stranger was
very strong, he killed about a dozen of bad desert bugs, one of them
had sweet bug juice, he didn't know so I stole it when he moved
on.

When he arrived to a crossroads strange people on strange animals
came and started fighting him. They beat him very bad. Then they put
him in a cage, like that one we put our sweet juice bugs in but it had
wheels. They talked a little bit. I had to hide because some of the
riders went my way. After they dragged him away I went the other way.
After one full day, hiding from people walking on the road, I've
arrived at a strange big village, it had tall walls all around
it. There were funny people with scary pointy sticks in front of the
door to the village.

Shortly after green I've crawled into one of the boxes on wheels that
were entering the town. The guards were searching the boxes. One of
them grabbed my foot when that happened... I felt strange tingling and
burning all around my skin when out of nowhere a green mist from my
palm flew into the guard's eyes, he immediately collapsed to the
ground gasping for air. I threw a shiny rock at the other guard, it
turned into a strange ball and then there was a flash so I ran away
deeper into the village.

I've ran for a while then hid in one of the strange big shacks. It was
so dark in there I could not see my hands. I've searched the shack and
found something soft I could lie on. So I slept. I was dreaming of
having wings, flying above a strange land. It looked like moving dunes
but very very fast and they were all blue, then I've continued to fly
over a desert that looked like after Green but brighter and the Green
was not even in the sky. I then descended to the desert and noticed
the desert had hair, like those animals that strangers ride on when
they pass through our village. I flew over strange shiny figures and
breathed out a strange cloud, the figures fell down immediately
grasping for air.

~interpunction, reword the dance part~
I then took off back into the air and met a strange green winged
creature that had huge head and mouth full of teeth, it had teeth on
its back leading to its long green tail connected with leathery stuff.
It looked exactly like me. When we got close, we started dancing. Twist
left over, twist right under, we took off twisting into the air until
we reached high clouds. Then we started slowly descending, I looked
into its deep green eyes it looked back into mine. It opened its
mouth and said: "Awaken!".

I woke up, observing Green slowly pulsating in the morning sky through
a hole in the boarded window. I've stretched my arm out toward it and
watched a green arm slowly extend out in front of me. That scared me a
little and the arm quickly retracted. I've turned on my back, closed
my eyes and slowly raised my hands above me. When I've opened my
eyes I was looking at a pair of green hands. They had scales,
like the creature in the dream but smaller, extending from back of the
hands, continuing up to the arms as far as I could see. The only place
with no scales were the fingers and the palms which were covered by
green skin. I've clasped my hands into fists, the hands immediately
formed fists. I've opened my hands back again, the hands
relaxed. Those hands were mine! My hands were green!

I've immediately sat up and realized that not only my hands but almost
my whole body was covered with green scales. Some of the scales were
small like my pinky toenail or as big as my big toenail. I've touched
my face and felt hard scales on my forehead as I was touching my face
some more I felt smooth skin around my eyes, on my nose and
cheeks. When I've reached my neck I felt hard scales again. I've
looked in front of me and on the opposite side of the room I've
noticed curled up skeleton, the white bones were stripped clean. Its
right skeletal arm was reaching for a necklace with big red gem. I've
stepped around it, very carefully, I didn't want a flesh flea to bite
me. I've reached out to the necklace and it was mine.

That is when the door to the shack opened and I've heard two pairs of
boots step in. I hid in the closet and stared outside through a small
hole. I watched two strong men enter the room I was sleeping in. They
noticed the skeleton near the wall and looked more closely. A black
shadow-like monster started crawling from behind the bones covering
the floor like a rug. One of the men called out something but it was
too late.

Small dots started jumping from the monster, they started screaming
but the dots entered their mouths and the men caughed. Blood was
coming out with each of their cough, the monster disappeared and their
bodies was crawling with flesh fleas. A horrible fate that reminded me
of our neighbor, we had to set his house on fire. One of the men
looked at me sitting in the closed horrified, he opened his mouth and
tried to say something but all I've heard was gurgling. I left the
closet and ran.

When I've peeked outside the shack door I saw two groups of similarly
dressed men walking from shack to shack. Were they looking for
someone? I ran thourough the village, people were stepping away from
me, my path was clear. I heard screams from around me as if the people
weer scared of me, I didn't pay attention to that. After a while I saw
a lot of men standing shoulder to shoulder next to each other blocking
the street. They were looking at me. I've turned around and ran
back. I ran for a short a while when saw another group of men doing
the same, they were coming closer. I've turned around and ran into a
small street but after a short while I've saw a shack blocking my
way. I had nowhere to run. Suddendly a hand extended from a shadow
under one of the shack, I've grabbed it.

It pulled me into a stinky dark room. After I could see in the dark
again I saw a boy. Loud noises started coming from the hole I was
pulled through, louder and louder. "Don't just stand here! They're
gonna catch us!" said the boy. And I ran through a strange tunnel that
looked a bit like our well but it was the wrong way! I followed him
for a long time, crawling through small windows, stepping over stinky
water. After a couple more of turns and climbing we've left the hole
and found ourselves back under the hot sun. We entered a shack with
strange symbols on the door and walked in front of three more boys and
two girls.

"Why did you lead her here, Jade? You clearly must know that it is her
whom are they turning the sity upside-down for?" said one of the older
boys.

"She could be quite useful to us." the boy who saved me said. "I've
seen what she caused at the gate, she easily killed two guards and
sneaked away. Even I had trouble finding her."

"Maybe! But what to do with her now? They are unlikely to stop until
they find her." responded one of the younger boys.

"We can exile Jack, he has been rotting in the cell of yours for days
anyway." Jade said.

"And how are you going to do that? Do you think the guards can be so
easily fooled now, that they've seen her?" said the older boy again.

"It is quite easy, we will tie sewer moss over his body and let him
escape through one of the tunnels leaving the city." Answered Jade "He
knows what happens to him when he returns and giving himself up to a
bunch of guards just gets him killed. Once they'll spot him running
away toward the desert worm plains they'll likely leave him alone."

"And I will spread rumors that it was her who ran towards certain
death." said one of the girls with big belly. "You're smarter than
I thought Jade!"

"Let's get to it! I don't want them entering our hideout again!" said
the younger boy looking straight at me "You better go help Jade
if you want to stay with us!".

"Here!" said the younger girl. She removed a board from the floor of
the shack and I could see a ladder leading under the shack.

"Let me go first" said Jade, grabbed a handle and helped himself into
the hole. I've carefully crawled one bar after another until I've got
to the bottom. When I've looked around I saw Jade removing stones from
a wall in the corner.

"So you already know my name. Sorry, there was no time for
introductions, and we are not out of the trouble yet." he said. "There
is a sewer tunnel behind this wall. In one of the dead ends is a boy
chained to a wall. I'm going to release him. Here is a knife, scrub a
bit of the sewer moss from the wall for me."

As he said that he crawled through the hole we made, I followed
him. The stink felt even worse than the first time. ~At an
intersection, jade left~ I've changed grip on the knife and started
scraping the green wall ~living from light coming through cracks~.
It was coming off easily. Before I could hear two sets of steps behind
me I had a reasonable pile of what they called sewer moss. I've
expected him to say something but the silence was only interrupted by
the steps.

I've looked over my shoulder and stared into two eyes reflecting a bit
of the dim light coming from above. It had long nose and whiskers
coming from one wall of the tunnel to the other. Fur coming from its
nose and disappearing in the darkness between its eyes. I've dropped
everything I had and ran forward. I've turned into a tunnel and kept
running. I've heard the steps coming closer. I put all my strength to
my legs and ran even faster. I've reached a room where there leading
three more tunnels out. I took my left. I took a couple more steps but
then slipped on a slimy pile of stinky goo and fell.

The creature jumped on top of me, scratching. I retched as the smell
~directly breathed at me~
from its mouth went directly to my face. I was looking at two huge
teeth coming out of the creature's mouth. As the mouth closed in on my
face trying to bite my head off I stabbed it with Jade's knife I
clenched in my hand. I felt the knife go in smoothly then hitting
something hard. The creature immediately backed up, revealing its
whole furry body. It was looking at me with anticipation ~?~, right
eye leaking out.

My heart was beating as the creature prepared to leap I put my hands
in front of me, trying to stop it with all my being ~this section is a
bit odd, but whatever~. My hands started glowing dark green, I felt
something as if my blood wanted to escape from my chest through my
arms and hands out of my body. A strange pulsating glowy liquid
escaped from my hands and hit the creature in its head, it entered
through its skin and left no trace. The creature started violently
shaking and fell on its back, twitching its huge dirty feet. I watched
as the twitching was slowing down until it completely stopped. ~fell
to the knees~ I've heard a familiar voice behind me "So you've met
Jake?".

~It's dark~
I've turned around and saw one of the boys that were with me in their
shack "You're surprising me, love! I thought Jade would've let you get
lost in the tunnels but you really do prove to be quite resourceful!"
he continued "Name's Bob, by the way! It looks like our Jade went too
ahead of himself again and forgot to tell you about our friendly
neighbor rat." ~slight contradiction here~ He looked down on the
creature's head "I have no idea how Jake escaped the barricaded tunnel
but it seems that the way under the Market is now open! Oh, and don't
worry, this is not the Jake we were talking about up above!". He put
his hand on my arm "Time to go love! You still have a Jake to kick
out! I'll take care of things so you can have a MEATY meal
tonight!". I stood up, the boy walked past me "Go straight, then take
two left turns then straight again and at an intersection with bright
light from above turn right. You shoud be back where you've started."

I've walked through the darkness, following Bob's directions. When
I've entered the bright room I saw a pile of sand underneath a mesh up
on the ceiling. Whh-PSHH! Sound came through the barred hole in the
ceiling. A face blocked the hole, I saw a woman breathing in and out
"Stop sniffing the shit down there and walk faster! The crops won't
harvest themselves!" a fainted voice from behind her said, then a shoe
with a hard kick moved the woman's face off the grate
~consistency~. After a short pause the voice, now more louder, said "Oh
yeah? And what you gonna do about it? Dan said that he's gonna go to
the market and buy more anyway!".

As I've continued to the right tunnel I've heard more moans and sounds
coming from above, as if someone was beating a sack of grain. I've
continued through the dark tunnel and reached an intersection where
were two figures waiting for me. "Hey! You've escaped! I thought
you're goner there!" said Jade and turned his head to the other boy
"Say hell to Jake ~Using the same name is confusing~ here! His
shackles were all rusted up so I needed something to break them
open. I guess the stone was important for the barricade that held the
rat on the other side." he explained "I guess it was not in the next
tunnel. Should've marked that." he jerked the chain in his hand in
front of him and the boy fell on his hands "Introduce yourself to the
lady!"

The boy slowly raised his head "So you're the witch that came here to
curse this city? Is it gonna be drought? Or are you going to infect
poor Jade with plague?" ~This is something that crazy old man would
say~

In that moment Jade kicked him in the face "Be polite! She is our
guest and you're going to be nice to her!"

He raised himself on his knees "So you've have already enchanted him,
huh? What a loss! He could be a nice thief if he hadn't his eye for
green monsters like you!"

"Alright! Now you've pissed me off!" Jade screamed and kicked him in
the stomach at full force.

The boy fell on his side "You better not finish me off here! I guess
you didn't cause youreslf so much trouble just to show me your new
girlfriend." came out of his mouth faintly.

~character conistency!~
"That is right Jakey! We're here to set you free!" Jade said and took
a proud pose! "That reminds me, we're quite in a hurry, would you mind
picking yourself up and get your ass moving?" He pulled on his chain
and made Jake, grabbing his throat, stand up. "Let's go! We have quite
a march in front of us!"

Jade led the way, we were walking through twists and turns. Crawling
through tight spaces and more dark tunnels. After some time we entered
a strange big room with ceiling supported by big rock. A big dark hole
opened in front of us.

"We call this the Dark Hole. We don't know what lives there but it
cannot be good. Here Jakey would tell you more if he wasn't a complete
nut job." Jade spat down into it then looked at Jake "If it is true
what James said about his race being noble protectors of the forests
then his kin would not be really happy with him ~why?~."

For the whole time we were walking around the Dark Hole Jake was very
quiet. Once we left through the tunnel leading out he started quietly
sobbing. We quietly arrived to an opening in a wall, when we crawled
through we found ourselves in a strange place. There were big stone
coffers. This whole place was very dark ~describe the darkness~ Jade
led us through dark corridor and then we found ourselves climbing
stone steps. I've tripped over a wooden thingy.

Jade put his chain in my hands and said "Don't let him run!".

He lifted the huge wooden thingy and pushed it into the ceiling, he
then started cranking a crank. A lot of sand started falling down but
he kept cranking away. After a moment a speck of light entered the
room that started slowly widening up. I could se Jake's face now. His
dirty face was revealing a deep black scar across his left cheek, his
hair was very uncombed, it was held back by his long pointy ears. His
eyes had no dots, they looked like glowing blue clouds. "Are you
putting a curse on me, witch?" he snapped at me and I've looked back
at Jade.

Clack! He finished doing his thing and picked up a ladder lying
alongside the wall, he put it inside wooden thingy that is now a
tunnel up. He grabbed moss from a bag he had strapped to his back and
started tying it around him with small threads. When he used up all
the moss he grabbed the bag and put put it on his head, secured it
with a thread, it looked like a hat.

Jade took the chain from my hand, looked at Jake and said "You're
gonna be free soon!".

~wait until early afternoon~
He started climbing the ladder, pulling on Jake's chain who was
climbing up behind him. I was slowly following them. We climbed up
next to a big hot rock. The sun was above our heads. "Give him your
waterskin!" said Jade. I removed my half empty waterskin from my
shoulder and handed it out to Jake.
~foreshadow bleeding~

~locate the city from this position~
Jade removed his bonds and said "You're now free! Go! And never
return!".

Jake responded "As if I wanted to stay with your witch!" and started
walking.

~notices injury from combat with rat~
We've climbed back down and sat next to a wall. I was looking at the
wall. There were strange statues in the side of the stone. It was a
group of people carrying a box. Inside the box I could see a
skeleton. There was a picture of a strange flying creature. ~discard~
I felt Jade put his hand on mine "I think they called this place a
crypt" he said "A place where they would bury their dead". After a
short rest I've helped Jade to remove the wooden tunnel from ceiling
and the room fell back into darkness.

After waiting for a while until I could see again, we started walking
down the stairs back, crawled through the hole we came through. As we
were walking around the Dark Hole strange faint noises were echoing
from down below. Like if someone fought a monster in the
distance. When were closing in on the tunnel leaving the Dark Hole we
could hear voices coming out.

"Are you sure it is safe down here? What if we get caught by the
sewer monster?" said one voice.

"And what do you suggest? To get burned alive by those purging fires
instead? There must be an exit around here somewhere." the other voice
replied.

We hid next to the entrance to the tunnel, our backs next to the wall
when we saw two figures come through, they've approached the Dark Hole
"How deep do you think this is?" said the shorter man.

"There is easy way to tell, just let me..." as he said that Jade
pushed him with all force into the hole.

~Rewrite, everyone is a badass after all~
The man started screaming, stepping away from the hole, looking around
himself erraticaly. But he couldn't spot Jade hiding in the darkness
next to him. Jade jumped on his back and stabbed him in the neck. The
man started grabbing which se succeded and threw Jade off of him. Jade
landed into a pile of dry refuse.

The man pulled something from his back pocket and jumped on Jade and
holding his throat said "You're not going to take me down that easily,
boy!"

Jade screamed, looking at me with his terrified face. The man followed
his gaze and looked at me. "So you're here with your whore! What if I
kill you in front of her?"

I fell to my knees "Please sir, don't kill him! He saved my life!"
I've started crying.

"Oh, what a honorable knight you are! I have an idea!" said the man
and grabbed a rope attached to his belt. "How about a tragic story
where the good hero was restrained and could only watch how his
princess gets molested in front of him!" he continued.
~and tortured~

I started crying even more "Please sir, let him go!".

The man tied Jade's hands to a piece of metal on the floor and
approached me. I felt strong hand grasping around my arm. "Don't worry
little one, it will only take the whole afternoon. I'm not in a
hurry." and put his other hand on my side. He leaned on me.

"Quickly! Kick that worm!" screamed out Jade.

~A bit cheezy~
I've extended my leg forward and kicked him in his leg. He laughed
"You can try as much as you want, they don't call me The Rock for
nothing". I fell forward but my arm was still in his hand. I've turned
around and stabbed him is the hand with a fragment of Jade's knife.

"Oh, no no no! You're not going to give her any more ideas" the man
yelled out and moved his hand from my arm to my wrist. He jerked me
and I fell on the dirty floor. "You stay there, honey! I'm not done
with you!" he said and with a full force punched Jade in his
face. Jade's legs became limp and he fell to his knees. "Good boy!
Don't worry! You can watch me and learn!" he said and walked up to
me.

"Please! Stop doing this! I don't like it!" I hid behind my crossed
arms.

~This encounter forces character development way too soon~
"Oh, that is because you never tried it before! I'm sure you will love
it!" said and grabbed both of my hands.

"I don't want to! Please! Let us go! Jade didn't want to hurt you! He
was just really really scared!" I cried out.

The man let go of my hands "Grab your piece of boyfriend and go!".

I've looked at him, confused. "Take that brat and leave at once!" he
repeated.

I took a knife from the pack hanging on my belt, gently rubbed
bunny on the blade and cut rope tying Jade's wrists together. I've
grabbed his hands and led him out of there. The man was just silently
standing there with crossed arms, looking in our direction.

We quietly walked through several tunnels when Jade whispered in my
ear "How did you do that?".

I shook my head. I don't know what happened there. The hole, the dirty
boy, the tunnel monster, the children, the scary men, the big
green creature, the elder guy. I don't know what had happened!

~it's not that late! or is it?~
We went through twists and turns. Crawled through tight tunnels and
found ourselves under a faint green light from above. The wall next to
us stil beared a marking of scraped of the moss. We're close!

We went into a tunnel, crawled through a hole, climbed up a ladder and
entered a familiar place. A girl with big belly was sitting in the
corner "They went out without you. They expected you will return much
sooner!" she looked at Jade closely "Did you get into a fight again?
You're lucky you have a new guardian angel with you."

She looked at me "I keep telling him to not pick fights with the
adults! That he's not gona return back one day!"

"And I keep telling you that if it weren't me, you would still had to
wait until dark to go out!" spat out Jade and sat on the floor. "Your
story about the sewer monster would just stay a fairy tale."

As I was sitting on my knees the world started disappearing in front
of me...

~Add dream scene here~

I slowly opened my eyes. I saw a person sitting beside me, all
blurry. She said something and put her hand and on mine. I've passed
out again.
~everything disappeared again~

~More dream scene~

I woke up. Sun shining in my eye through a crack in the roof. I looked
around and on my side was sitting the girl with big belly. "Finally!
You're awake!" She opened her arms. "Don't move just yet, I have to
remove that from you!" And she untied rugs around my arms. "You've
nearly set the roof on fire" she continued and pointed towards a black
spot on a wall across from me.

I sat up... a horrendous pain entered my head. I sat there for a while
waiting for the pain to stop. The girl brought me a flatbread and a
cup of water. "Eat! You have been sleeping for nearly two weeks!" I've
put the cup in my dry mouth and drank all the water in three long
gulps. "Drink slower! We're low on water since Jade got captured!"
Said the girl. Darkness fell over my head...

Now two girls were standing over me. "Poor baby, she passed out as
soon as she head that Jade is gone." said the girl with big belly to
the other then looked at me "She's waking up, get me that stool over
there!" the other girl disappeared, I've heard some creaking and
shuffling and then the girl sat next to me. "You haven't eaten yet!
Take this! You must strengthen up!" and handed me a piece of
flatbread. I put it in my mouth and started munching on it. It was a
bit hard and dry. I've got handed a cup of water, it helped me to
soften the bread a little bit. And with each gulp I ate more and
more. Then my belly started hurting a little bit and I burped.
~Water supply is low, idea: she hates this kind of bread~

"You're not used to eat that much. You will need some more time to get
to your full strength" said the blonde girl. "Do you think you can get
up?" she said.

I sat up, my head started hurting again but I could bear it. I put my
hands on my head so it would hurt less. After a while I put my feet on
the ground, I felt cool ground underneath me. I've looked around and
spotted loose stones in the wall with black shadows between the
cracks. There was a ladder in the opposite corner. We were in the
basement!

"You don't have to climb upstairs just yet!" said the girl with big
belly and continued "I can call others and we can meet down here."

I've nodded and put my hand on my chest. It was bumpy. I had a lot of
small hard bumps nearly all over my chest. I've looked down, I had
scales there. But around my breasts didn't have scales I had green
skin there. The green creature! My left breast had thick dark green
line across my soft green skin. I tried to scrape it off but the
blonde girl stopped my hand and said "If you scratch it off you'll be
bleeding again!".

"But I don't want this... Moss on me!" I've replied.

"That is not moss that is your hardened blood." she said "It is like
me or Sophia when we get hurt it bleeds but then the blood hardens and
turns dark red. But your blood is dark green so when it hardens it
stays like that!"

"Am I a monster?" I've asked. I did not like it! I wanted to be with
my mommy in my village catching desert bug nom noms for auntie
Theresa! ~change it~ Sadness came over me and I started crying.

"Hey! Stop being a crybaby!" A voice said. I've looked up and I saw
the boy quickly crawl down and continued "I loved how you killed the
huge ass rat! The rat was like this" he imitated the animal with his
hands and stretched face "And you were like this!" He crossed his arms
"And then you were like bzzzt! And the rat was like this" He dropped
on his back and twitched his arms then jumped back up and said "And we
had food for like a week!".

"Yes, we know, David! You were telling the story every day!" said
another boy that crawled down after him.

"She is just so awesome! Can we keep her? Please! Please! Please!"
said the boy.

"That depends on what she can do. Now that Jay is not here we are
having trouble getting water." said the older boy "She would have to
learn a job so one of us can take care of getting water."

"I'm sorry, but I cannot keep the bargain we had at the beginning." He
continued "The water well in Nightfall district dried up when they
burned it down and getting water is very hard now"

"Yeah! Only the Lord district has water now, I saw them giving out
water to people. They have giant pot surrounded by guards." Said the
boy "When I tried to stand in the line they kicked me out and said
that it's only for grown ups"

"I've been there too and they gave me a cup!" Said the girl with big
belly.

"That is because you're carrying our baby!" said the older boy
"Everyone knows that mothers have it easy!"

"You know nothing about carrying a baby, James!" she snapped back.

"Well... This could be our solution!" the boy clasped hands.

"I think that's stupid! What do you want to do? David is not big
enough to make a baby with Jasmine and she is too young!" she replied.

"And doesn't it like... take a long time before you look like you're
having a baby?" asked the younger boy "What about giving them meat? I
have some salted stashed away."

"And how do you think that would happen? You walk up to the guards and
say Hey! Give me water! I have meat!? They would catch you and make
you a slave!" said the older boy.

"I know a guy in the merchant district, he could help us! I was
there with my father to pick up a package!" said the blonde girl.

"And how do you think how he could help us?" said the older boy.

"I was helping my father in the kitchen, he always had some meat in
his house" said the girl.

"But we aren't hunters and getting outside would be too dangerous! We
could get spotted and taken away. Only the crazy people go out hunting
in the desert" ~who's saying this?~

"And where do you think you got your latest meal from? Yes, we have
pretty capable sewer hunter right here!" said the younger boy and
pointed at me.

"Are you crazy?" said the girl with big belly "She is too little to be
hunting tunnel rats! The rats are capable of killing two grown ups! We
were lucky that we were able to lock them away from our tunnels!"

"I guess our situation gives us little choice. Are you able to hunt
sewer rats for us?" the big boy looked at me.

I sat there, looking at him with open mouth. I've remembered the eyes
in the dark, the big scary white teeth and the horrible stench from its
mouth. "No! I don't want to go back there! Please!"

"I guess this is a no then!" said the older boy.

"What did you think? She is not in a condition to do any of this
stuff!" said the girl with big belly. "There! There! It's okay." she
put my head on her chest. I felt a bit better.

"Your head is very hot, you should get back to sleep!" she said and
helped me to lie back down.

"Meeting is over! If you want to continue, take it back upstairs!"
I've heard her say. Then there was some noise, some clanging from
above and then some quiet creaking from the ceiling. I fell asleep.

I was dreaming of the monster. ~figure out what exactly~

I woke up after Green. I quietly crawled up the ladder to the floor
above. In the faint green light from outside I could see a
staircase. Only the tower in our village has a staircase, in here even
the poor houses have a staircase. I walked upstairs. I've entered roof
flooded with green light. The girl with big belly was lying on her
back, staring up in the sky.

"I wish I could be a star." she said "I would just sit there in the
sky, looking how mortals live and die."

"Is this the best life we could have? Struggling every day for a
couple drops of water. Now they want you to hunt rats in the
sewers. Why can't we have enough water for everyone?"

"This is what we have. This way it always been" I said.

She looked at me "Nuh uh, there must have been much more water
before. Jay once said that he found a strange stone with pictures, he
said that the sewer once exitted into water."

"Wow! Really!? I want to see it!" I exitedly said.

"Only Jay knows where it is. And Jay is gone." she hid her face with
her arms.

"You're awake!" I heard from behind. "Our request must have given you
nightmares. You were crying out of your sleep!" he said with sadness
in his face.

"You don't have to do it! I will send David to the sewers!" you can
steal from houses!

"James! She cannot be seen like this!" said the girl with big belly in
annoyed voice.

"We put something over her!"

She knocked herself on the head "Yeah and attract even more attention!
And the heat wearing such a thing would kill her!".

I've shivered. The Green is usually nice and warm but now it is just
cold coming from it.

The girl with big belly put her warm hand on my leg "You're
shivering!" she said "And your scales are so nicely cold.". "Come lie
next to me! I want you to cool me down.".

I lied next to her, she put her warm body over me. "Your scales are a
bit rough!" she whispered. I felt small bumps pressing into my body, I
will never get used to my scales! I felt a lot warmer tho.

"Is this good?" I've asked.

"Shhh!" she put her finger on my lips.

Her hand fell off my face and I was staring into Green, slowly
pulsating in the sky. Releasing its balls of light and fading away. It
was so peaceful.

I was woken up in the morning by noise coming from the street. The
girl with big belly was still sleeping on me. I didn't want to wake
her up.

"He stole water from a pregnant girl" I've fainty heard a female voice
from below.

"As if there wasn't enough of them. Let the boy go!" said other female
voice.

"You know they can't do that." replied the first voice "If we don't
punish it soon everybody will be stealing not just from the poor but
even from us!"
~What is the point of this conversation?~

Then I've heard a lot of people repeating "Dry rag! Dry rag! Dry rag!"
over and over again. I've heard the noise slowly fading away. Later I
could hear "Dry rag! Dry rag! Dry rag!" very faintly. I passed out.

I woke up when I saw the girl's with big belly face in front of mine.

"I haven't slept this good for a long time" she said with a
smile. "I'm definitely up for doing it again"

She slowly stood up "I have work to do. See you later" and with those
words she dissappeared inside.

"You two were there so cuddeld up" said the younger boy ~who?~ "It was
so cute!" and smiled.

"We're going to try to trade some meat for water" he said while
scratching his back "Are you coming with us?"

~Makes little sense, she just woke up~
I've got tired of staying in here for that long. I've nodded and
followed him downstairs. He opened a door and I saw a room full of
drying meat hanging on numerous threads.

"See the fruits of your labor. Or bloodlust shall we say!" He said
with a chuckle. "The bad news is that the best parts were already
eaten by maggots when you killed it." he continued.

"Here have a bite!" he removed a flank from the thread and handed it
to me "It's so much better fresh but you've missed the opportunity".

I've remembered ~something~ from my dream. I bit into the meat, it was
tough but the flavor filled my mouth. It tasted nothing like desert
bug nom noms. 
~finish this~

"Will you just stand there?" he tapped my shoulder "Here, help me with
those!" he said and wrapped a thread with meat around my shoulders. I
felt its weight, it was like carrying two jugs of water.

He took two such threads on himself and then I've followed him
downstairs, there the blonde girl was preparing a couple of sharp
sticks.

"Those will make it easier to carry the meat" said the boy.

He saw me gazing at the nearly a dozen of sticks and said "The rest is
to defend ourselves with. We're going through the sewers and who knows what
else is down there."

"Why can't we go through the streets?" I've asked.

~tweak it~
"Some people are bigger monsters than what you've fought down
there. Besides, you're one of them too." said and looked at my
hands. My scales!

"How did you escape for so long?" asked the younger girl. I've looked
at her, I had no idea what she's talking about.

"You're a... a... monster. How could people not catch you sooner?" she
asked again.

"She was not like this. Jade said that she looked like regular girl
when she escaped from the gate." said the boy "When we met her she was
newly transformed."

~rewrite this garbage~
Am I a monster? I never thought about it like that. But it all makes
sense now, why they were hiding me for so long. Didn't allow me to go
outside to greet the sun. I am a monster!

~salvageable?~
I was supposed to be beautiful, to grow up and make lots of babies!
How can I find a boy now? Who would marry a monster?

"Here! Hold this for me" Said the boy and gave me one of his meat
threads.

My knees faltered ~is this the word?~ under me a little bit. He then
took one of the sticks and pushed it through all the meat on his
thread so much so that there was a bit poking from the last meat. He
removed the thread and squished the meats together. It formed
~something~. He had done it with the meat I was holding with me and
when he was done we and the blonde girl started climbing down the
ladder, helping so that we won't drop the meat on the ground.

We carefully pulled the meat through the hole in the wall and put the
bricks back. We were carrying them on our shoulders between us, the
girl was in front with two sticks on her shoulders, two more in her
hands, the boy three sticks while I was carrying the end of the meat
between us.

We were slowly walking through the dark tunnels. I had recognized the
intersection where I scraped the moss off but there was growing new
bright green moss, like the edges of the Green. We walked through a
couple of intersections when we encountered a strange hole between
something that looked like piles of rocks and strange moss covered
wood.

"So it pushed the block away." Said the boy "I swear I had secured it
correctly!"

He looked around in the dark and said "Girls, I'm gonna need your
chest rags!".

"What? So you coud look at us? Pervert!"

"No! I need to put this down so we can clear space around the
barricade. And I'm not putting it in the filth!"

I've undone my chest rag with one hand threw it in front of me.

"Not me! I have to hold the racks somehow!" he said and threw it back
at me. "Just try to spread it as best as possible so it covers the
ground."

I tried my best but it was not enough.

 "I said I'm gonna need your chest rags!" said the boy again.

"Ugh... okay.." said the girl and started undoing her chest rag.

Then she threw it behind her, The boy in a quick motion threw her
chest rag. It landed on my face. 

"Put this one down too" he said.

I tried to spread it with my feet again. It was pretty difficult, the
rag kept sticking to my feet but I managed it.

"Good. Now grab your rack and put it down!" Said the boy to me.

I pulled on the rack.

"No! You're gonna drop it! Grab it closer to me first!"

~Make them carry twice as much~
I dropped my sharpened bone sticks, lifted the rack from my shoulder
and grabbed its other side with my other hand. It was soo heavy!

I carefully laid it on the rags. Then I've observed the boy with the
girl grabbing rack on tehir right shoulders and carefully lay it next
to mine, then they proceeded with the other one.

"Ewww! My chest rag is completely soaked in this stuff! You're gonna
get me a new one! And for her too!" Said the girl.

I shrugged, what is the big deal? We're not that different from boys
anyway!

"Later, now I'll need your help to clear out the rocks. Since our lady
here already got us rid of the big rat we can safely remove it" He
said and started digging in the pile. We were helping him carrying
stones and planks away.
~add poop encounter~

"Good it's done, let's look ahead a bit" said the boy.

"Shouldn't we have done that before we were carrying the meat in here?
It may attract rats and who knows what else." Said the girl.
~it is a bit odd in here~

"Aren't we doing it now?" asked the boy.
~finish this exchange~

I followed closely behind him with my dirty bone sticks, there is
something gooey on it! Ewww!

We went through a couple of tunnels but heard nothing saw nothing. It
looks pretty safe. We entered into a room with dim light coming from
above, there was a pile in the middle. I saw a big four-footed monster
munching on something quietly.

"Shh" whispered the boy to me "Let's not disturb it! Those things can
get pretty dangerous when you piss them off."

~meh~
I felt something on my neck, it was getting really itchy when the girl
screamed. I grabbed the thing but I couldn't remove it. It was stuck
to my neck! I started screaming in horror!

I looked up. There were black spots slowly moving above us. One of
them dropped on us, two, three! We quickly ran back to the tunnel. We
heard something loudly pacing behind us. Then we heard the shriek!

"Told you don't piss off the rat!" said the boy.

We ran into another lit tunnel, this time the light was coming out of
an enclosement in the wall. I tried to hide in there but the boy
grabbed me by my hand.

"Don't try to fool yourself, you cannot hide from these things!"

~Recall action with bugs from home~
And as he said that the monster jumped on the back, he fell on his
face in the nasty mud. I pierced the monster's belly with one of my
sharpened stics. It shrieked and looked at me. It showed me its nasty
teeth. I jumped on me.

I tried to block it with my arms. It bit to my left arm but I felt
only small pressure. My scales protected me! I tried to shake it off
but it was still hanging from my arm. It was so heavy!

~combat is supposed to be less clear~
I saw the boy stand up, he took a stick from the girl and pressed it
into the monster's head from behind. It immediately released me and
fell to the ground.

"Show me your arm!" he said and examined it.
~What happened to the leeches?~

"It has done nothing to you! Next time you're the shield!" he said
with laugh in his voice.

"What?" I exclaimed in confusion.

"You're invincible! You get to protect us!" he said.

"Invincible?"

"Yeah... like... nothing can hurt you!"

"Nothing?"

"Yes! Nothing! Oh, don't worry about that, we will find something to
cover that!" He pointed at my breasts.

"Uhhh?"

~it is a specific character~
"I will explain it later! Now we should get back and get the meat. The
trader is up here."

We went through a couple of tunnels and came out near our stuff. There
were small things munching on it.

"No! Get away! Hush!" The boy started smacking them with his stick.

"Go away!" said a looked at the meat.

"Oh no! There is not much left!"

He picked up one of the meat sticks. It was covered in sticky goo and
smelled horribly. Eww!

"Looks like there is something left on the rest of the two!" He took a
clean stick from Jane's hands and started moving the meat from the
old sticks on his new.

"It's not really that much. I can carry it on my shoulder."

"So what do we do now?" asked Jane.

"We bring him what we have." Said the boy with decisive voice "We
should have done it this way in the first place."

So we followed him through the tunnels until we arrived under a
strange grate, unlike others it was made of wood and it was broken. We
pulled ourselves through upstairs and found ourselves in a trashed
room. ~describe~ There were large scratchmarks all over the place.

The boy knocked on the door.

"It's the damn rat agian! Gerald! Come put the closet back to the
door!" a harsh female voice came from behind the door!

"Hold on! Mother! I will be right there!" said another male voice.

Then tere were some shuffling noises.

The boy knocked again "We're bringing you meat!".

There was silence!

"Why should we trust you? You got in through the sewers. How do we
know you didn't come to murder us?"

"Hey! I'm in here with him!" said the blonde girl.

~I've got the names mixed up now!~
"Is that you Janet?"

"Yes miss Anderson! It's me! I'm here with my friends!"

The door opened.

"Come in! Come in! Before the sewer monster gets inside! OMG, it
really trashed it here!"
~This is getting too cheezy~

We entered a smallish kitchen with one very really shiny pot and
multitude of clay ones. There was light coming in through a window
with glass in it. They must be rich!

"Are you bringing us the witch? You're going to be rewarded
gracefully!"

The boy looked at me with fear in his eyes then back at the lady.

"No! We've come to make a deal!"

"What kind of deal? You can be handsomely rewarded if you give her to
us!"

"We... came... to sell meat." stuttered out the boy.

"If I accept your deal, what can you offer us to not mention that
you're affiliating with witches?"

"Excuse me?"

"You will have to pay us so we won't tell guards! Understood?"

He slowly raised the meat he had on the stick "Is this enough?"

"My dear, that is not nearly enough!"

"What do you want then?"

"Her!" she slowly pointed at me with her finger.

"She will do a thing here and there for us and you get your water!"

"But what if something happens to her?" said the girl.

"Pray that it won't!" the lady cut back.

"My Boy! Bring me a bucket!" she ordered to the man.

"Yes! Mother!" And disappeared in a door in the back.

"I will give you half a bucket of water. Return it back after Green
and you get the other half." She fixed her apron and looked at me "I
will have a small job for our treausre here. If you succeed, you get
water for months. If you fail, get ready to get out of here in
chains!"

With that, her son returned with a bucket full of water. She took it
for him and poured half into another bucket full of dirty dishes.

She handed it to us, "There you go! Now, leave!".

We slowly entered their messy room, let ouserselves back through the
hole and entered the dark tunnels underneath.

"Damn they're rich!" Said the boy, "You have such rich friends!"

"They're not my friend!" answered the girl with her finger on her
lips, "Stop talking like that!".

"What? Don't you want everyone hear that you have..."

"No! Stop talking like that!" she put her hands over her ears and ran
away.
~The two girls escaped together~

"Follow her! I need to take this bucket." Said the boy.

~pacing~
I went after her. I followed her sobs. Took a turn at an
intersection. The crying became fainter and fainter. It stopped. I
heard scream. Now I was running. I entered a large room and saw a huge
monster biting on something.

"Help!" echoed from behind the monster.

It was her! I've raised my remaining stick and lunged at the
monster. I've stabbed it right into the butt. It straightened up and
started looking around. It could not spot me. It started digging
again. Now I've heard a scream of pain. I didn't know what to do. I
walked around the monster and threw myself between it and whatever it
was biting on. I was scared.
~She won't remember this part ^~

The monster grabbed me in between its teeth and I've heard "What are
you doing?". I've blacked out.

~Dream sequence, recalling what the boy said about being invincible~

"Hey! Wake up!" some one shaked with me. I looked up. I was back at
the house, the girl with big belly was standing over me. "You have to
go to the lady! Janet told me you made a bargain. It's getting late!"

I tried to get up but my legs didn't listen and the headache!

"Slowly! You got beaten pretty bad. They found you in the sewers lying
beside Janet. It's a miracle you got out alive!" She lent me a hand
and helped me to sit on a chair. "I will give you a short while to
recover. Janet is waiting upstairs, she wants to talk to you."

And with then she crawled upstairs. Janet got down, looking with
sadness in her eyes.

"I'm sorry I got you nearly killed." She said looking down.

"It's just... They are not my friends."

"I will tell you a secret." she whispered in my ear "It was not that
my dad worked with them. They had a lot of meat all along. I got there
because my father was drinking a lot of beetle wine. He couldn't buy
any so he exchanged me for a jug. He told me he would come back but he
never did."

Her eyes started sprouting tears "They have told me that I have to
obey their customers or that they're going to never give me back. So I
did as they said... I was obedient to the customers. They.. done
horrible... things to me. Day after day, night after night. But my
father never returned."

She started sobbing.

"That was.. when I met Jane. She had... her belly... much
smaller. They were beating her... very badly. I grabbed her... hand
and we escaped."

Now she was all out crying.

"You could have... ended up... like Samantha... because of m... m... me!" she
fell to her knees "You are s... s... so... small... like her...".

"Hey! What did you do?" a voice from upstairs said. The boy crawled
down the ladder.

"You weren't coming back for quite some while so I was worried. When
I've returned I found you lying in the sewer, everything was
completely charred there."

He looked straight into my eyes "Tell me! Tell me! Tell me what
happened!"

"I don't know... I cannot remember."

"Aww... c'mon! If Janet didn't tell me I've hoped you would! You're no
fun!"

Janet looked at him.

"Oh yeah! You have to go to the lady! Janet wouldn't shut up about
it... that you must hurry... or she will do bad things and blah blah
blah..." and with that he straightened up and offered me a hand.

"Let's go! I don't want Janet on my neck all the time!"

I slowly grabbed his hand and he pulled me on my feet. I faltered a
bit but I stayed standing.

"You look a bit rough. Let me carry you so the lady won't get
disappointed."

He offered me to ride his back. I gladly accepted and slowly grobbed
him by the neck, he held on to my legs.

"Your scales sure are a bit rough! You coming?" He looked at the girl,
she shook her head.

"Alright, stay here! We will be back soon! Shiny, watch your head!"
and with that he walked through the hole in the wall.

"It's a bummer you don't remember! I told my big bro about you and he
would like to meet you!"

"Your big brother?"

"Don't worry he can keep a secret. When Ma and Pa died they took my
brother and made him a city guard. Then they moved in some rich
folks that wanted me to carry and clean stuff for them. So I ran. I've
escaped beating this close!"

He dropped my legs. "Sorry! I'm not used to carry people... Better?"

It was much better. My headache stopped, I let my head rest on his
shoulder.

"Hey! We're nearly there, get down. I'll boost you up!".

I got down, he prepared his hand to make a step. "You can step on my
shoulders, it will be much easier!"

I've done as he said and I was back in the trashed room. The lady
stood there with a broom in her hand. "There you are, I almost thought
that you changed your mind!". She put the broom next to the door "Tell
the boy that I won't be needing him, he can come back tomorrow morning
to pick you up!"

"I came as you wanted. What do you want of me?..." I said and
remembered what Janet told me about herself. I trembled.

She looked at me "Don't worry sweetie! I am more interested in what
you can do for me, not my customers!"

"Now, throw that rag away, I have something more interesting for you!"
And she grabbed my waist sash and tore it off.

"Very interesting!" She looked closely at my scales around my
hips. "Anyway! Get yourself dressed! There is something waiting for
you in the kitchen."

She turned around and walked upstairs somewhere. "I'll make you
privacy!" and closed the door behind her.

I found two pieces of clothing over the kitchen chair. The first one
was really long, so I've carefully wrapped it around my waist an my
chest. Then there was this other piece which was a little big but had
two ends. I put my arms through both of the holes, and wrapped the
ends around my wrists. Underneath was a round thing, it was really
soft! I put it around my neck.

With that I walked up stairs where I saw the lady disappear. There was
a long tunnel with doors in the walls. I walked past one and in the
left tunnel I saw a strange thing. I came closer. It was somebody!
They looked at me through a small window, coming closer as I was
coming closer to them. It was a girl with strange green face.

As we were coming closer to each other I could see better. Her face
was a bit dirty but under that dirt was green skin shining
through. But her eyes! Her eyes were faintly glowing in the weak light
of a candle. Her eyes were like the Green but much darker and calmer
as the rest of the dark sky. She had lumps on her forehead...
~Describe the clothes a bit~

Door opened behind me. "I sene you're enjoying yourself in the mirror!"

I turned around. I saw the lady standing there looking at me.

"But sweetie! That is not how you're supposed to wear clothes!" She
said in a high pitched voice. "Take it off!"

I was starting to take the clothes off.

"No wonder you live on the streets. Your parents didn't even show you
how to dress!" She said with a strange voice. "Come, I'll help you!"
she said and invited me to her room.




* Female Elf Ranger - Hunter (sister)

Rangers used to be guarding remote areas away from
civilization. Nowadays when civilization is not as common as it used
to be. People who managed to survive by themselves in the scorching
desert are now called rangers. 

** Appearance

** Backstory

I was born as a slave, my brothers were born as slaves, my parents
were slaves. We were forced to do XXX even during the hottest
days. One day my daddy was caught stealing water from the irrigation
canal.

That's when they locked us into that stinky shack without food or
water. The stink of rotting meat coming from the poop hole was
unbearable for the first three days. My daddy succumbed to madness, he
could not bear the situation he got his family into. When I woke up I
found him in the corner of the shack with crushed skull and bloody
rock in his hand. The same day my youngest brother died to an illness,
could that be because his leg slipped into the poo hole a day earlier?

My mother was stone faced nearly the whole time, even after father's
death she was calming us down, putting us to sleep and singing
lullabies with her drying voice. She could not bear the death of her
youngest son, however. She started crying and never stopped. I woke up
in her dry thin arms by insects feeding on her eyeballs. That was the
first meal I and my brother had in two ten-days.

Early in the afternoon the slavers kicked us out and made us carry the
corpses of our parents and brother, they were unusually light, yet it
took a lot of strength to lift them. When I looked back I saw another
family being led in.

We laid them on an edge of irrigating channel where most of the corpse
eating insects stay



* Male Elf Barbarian (brother)
